//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Character {
    
    private CharacterCustomization customizationField;
    
    private string[] gearField;
    
    /// <uwagi/>
    public CharacterCustomization Customization {
        get {
            return this.customizationField;
        }
        set {
            this.customizationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public string[] Gear {
        get {
            return this.gearField;
        }
        set {
            this.gearField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CharacterCustomization {
    
    private string raceField;
    
    private string genderField;
    
    private string classField;
    
    private int skinField;
    
    private int faceField;
    
    private int hairField;
    
    private int colorField;
    
    private int facialField;
    
    /// <uwagi/>
    public string Race {
        get {
            return this.raceField;
        }
        set {
            this.raceField = value;
        }
    }
    
    /// <uwagi/>
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <uwagi/>
    public string Class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <uwagi/>
    public int Skin {
        get {
            return this.skinField;
        }
        set {
            this.skinField = value;
        }
    }
    
    /// <uwagi/>
    public int Face {
        get {
            return this.faceField;
        }
        set {
            this.faceField = value;
        }
    }
    
    /// <uwagi/>
    public int Hair {
        get {
            return this.hairField;
        }
        set {
            this.hairField = value;
        }
    }
    
    /// <uwagi/>
    public int Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <uwagi/>
    public int Facial {
        get {
            return this.facialField;
        }
        set {
            this.facialField = value;
        }
    }
}
