//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class JewelryItems {
    
    private JewlryItemsJewelryItem[] jewelryItemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("JewelryItem")]
    public JewlryItemsJewelryItem[] JewelryItem {
        get {
            return this.jewelryItemField;
        }
        set {
            this.jewelryItemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class JewlryItemsJewelryItem {
    
    private string idField;
    
    private string nameField;
    
    private int qualityField;
    
    private string iconField;
    
    private int allowableClassField;
    
    private int allowableRaceField;
    
    private int maxCountField;
    
    /// <uwagi/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    public int Quality {
        get {
            return this.qualityField;
        }
        set {
            this.qualityField = value;
        }
    }
    
    /// <uwagi/>
    public string Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <uwagi/>
    public int AllowableClass {
        get {
            return this.allowableClassField;
        }
        set {
            this.allowableClassField = value;
        }
    }
    
    /// <uwagi/>
    public int AllowableRace {
        get {
            return this.allowableRaceField;
        }
        set {
            this.allowableRaceField = value;
        }
    }
    
    /// <uwagi/>
    public int MaxCount {
        get {
            return this.maxCountField;
        }
        set {
            this.maxCountField = value;
        }
    }
}
